require File.join(File.dirname(__FILE__),'hive-thrift-client','facebook_service')
require File.join(File.dirname(__FILE__),'hive-thrift-client','fb303_constants')
require File.join(File.dirname(__FILE__),'hive-thrift-client','fb303_types')
require File.join(File.dirname(__FILE__),'hive-thrift-client','hive_metastore_constants')
require File.join(File.dirname(__FILE__),'hive-thrift-client','hive_metastore_types')
require File.join(File.dirname(__FILE__),'hive-thrift-client','hive_service_constants')
require File.join(File.dirname(__FILE__),'hive-thrift-client','hive_service_types')
require File.join(File.dirname(__FILE__),'hive-thrift-client','queryplan_constants')
require File.join(File.dirname(__FILE__),'hive-thrift-client','queryplan_types')
require File.join(File.dirname(__FILE__),'hive-thrift-client','serde_constants')
require File.join(File.dirname(__FILE__),'hive-thrift-client','serde_types')
require File.join(File.dirname(__FILE__),'hive-thrift-client','thrift_hive')
require File.join(File.dirname(__FILE__),'hive-thrift-client','thrift_hive_metastore')
	